package ui;

import java.text.DecimalFormat;
import java.util.HashMap;
import java.util.Map;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.toedter.components.JSpinField;

import entites.SanPham;
import service.Sanphamservice;

public class ModelDanhSachSanPham extends JFrame {
	private Sanphamservice service = new Sanphamservice();;
	private Map<Integer, Integer> map;

	/**
	 * Creates new form ModelDanhSachSanPham
	 */
	public ModelDanhSachSanPham(Map<Integer, Integer> mapResult) {
		setResizable(false);
		map = new HashMap<Integer, Integer>();
		if (mapResult != null) {
			map.putAll(mapResult);
		}
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	private void initComponents() {
		jScrollPane1 = new javax.swing.JScrollPane();
		tablemodelsanpham = new javax.swing.JTable();
		txtsearchsanpham = new javax.swing.JTextField();
		btnsearch = new javax.swing.JButton();
		lblnhapsoluong = new javax.swing.JLabel();
		cmbsoluong = new JSpinField();
		btnthemvaohoadon = new javax.swing.JButton();

		this.addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				ModelCreateHoaDon createHoaDon = new ModelCreateHoaDon(map);
				createHoaDon.setVisible(true);
				dispose();
			}
		});

		btnthemvaohoadon.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				int row = tablemodelsanpham.getSelectedRow();
				if (row == -1) {
					JOptionPane.showMessageDialog(null, "Chưa chọn sản phẩm để thêm");
				} else {
					int id = Integer.parseInt(tablemodelsanpham.getValueAt(row, 0).toString());
					int soluong = (int) cmbsoluong.getValue();
					JOptionPane.showMessageDialog(null, "Add success");

					if (map.containsKey(id)) {
						map.put(id, map.get(id) + soluong);
					} else {
						map.put(id, soluong);
					}
					map.forEach((k, v) -> {
						System.out.println("result sau khi them:" + k + " " + v);
					});
					
				}
			}
		});

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		tablemodelsanpham.setModel(new javax.swing.table.DefaultTableModel(new Object[][] { { null, null, null },
				{ null, null, null }, { null, null, null }, { null, null, null } },
				new String[] { "ID", "Tên sản phẩm", "Đơn giá" }) {
			boolean[] canEdit = new boolean[] { false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(tablemodelsanpham);

		loadDataTable();

		btnsearch.setText("Tìm");

		lblnhapsoluong.setText("Nhập số lượng :");

		btnthemvaohoadon.setText("Thêm vào hóa đơn");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(10, 10, 10)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup().addComponent(txtsearchsanpham)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btnsearch))
								.addGroup(layout.createSequentialGroup().addComponent(lblnhapsoluong)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(cmbsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(btnthemvaohoadon)))
						.addContainerGap(10, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(10, 10, 10)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txtsearchsanpham, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnsearch))
						.addGap(10, 10, 10)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(lblnhapsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 20,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(cmbsoluong, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnthemvaohoadon))
						.addContainerGap(10, Short.MAX_VALUE)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ModelDanhSachSanPham.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ModelDanhSachSanPham.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ModelDanhSachSanPham.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ModelDanhSachSanPham.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ModelDanhSachSanPham(null).setVisible(true);
			}
		});

	}

	private void loadDataTable() {
		// TODO Auto-generated method stub
		DefaultTableModel model = (DefaultTableModel) tablemodelsanpham.getModel();
		model.setRowCount(0);
		for (SanPham sanpham : service.getDanhsach()) {
			model.addRow(new Object[] { sanpham.getMasanpham(), sanpham.getTensanpham(), formatMonney(sanpham.getGia()) });
		}
		tablemodelsanpham.setModel(model);
	}

	public String formatMonney(double money) {
		DecimalFormat df = new DecimalFormat("###,###,###");
		return df.format(money);
	}

	// format string to monney
	public double formatStringToMonney(String money) {
		String[] arr = money.split(",");
		String result = "";
		for (String string : arr) {
			result += string;
		}
		return Double.parseDouble(result);
	}

	// Variables declaration - do not modify
	private javax.swing.JButton btnsearch;
	private javax.swing.JButton btnthemvaohoadon;
	private JSpinField cmbsoluong;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lblnhapsoluong;
	private javax.swing.JTable tablemodelsanpham;
	private javax.swing.JTextField txtsearchsanpham;
	// End of variables declaration
}
