package ui;

import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import entites.ChiTietHoaDon;
import entites.HoaDon;
import entites.KhachHang;
import entites.SanPham;
import service.ChiTietHoaDonService;
import service.HoaDonService;
import service.KhachHangService;
import service.Sanphamservice;

public class ModelCreateHoaDon extends JFrame {
	private DefaultTableModel model = new DefaultTableModel();
	private String[] columnNames = { "STT", "Tên sản phẩm", "Đơn giá", "Số lượng", "Thành tiền" };
	private Map<Integer, Integer> mapHD;
	private Sanphamservice sanphamservice = new Sanphamservice();
	private ChiTietHoaDonService chiTietHoaDonService = new ChiTietHoaDonService();
	private HoaDonService hoaDonService = new HoaDonService();
	private KhachHangService khachHangService = new KhachHangService();

	public ModelCreateHoaDon(Map<Integer, Integer> map) {
		setResizable(false);
		initComponents();
		if (map != null) {
			mapHD = new HashMap<Integer, Integer>();
			mapHD = map;
			map.forEach((k, v) -> {
				SanPham sanPham = sanphamservice.findById(k);
				model.addRow(new Object[] { model.getRowCount() + 1, sanPham.getTensanpham(), sanPham.getGia(), v,
						sanPham.getGia() * v });
			});

			tableModelCTHD.setModel(model);
			tableModelCTHD.updateUI();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		lbltenkhachhang = new javax.swing.JLabel();
		txtsodienthoai = new javax.swing.JTextField();
		lblsodienthoai = new javax.swing.JLabel();
		txttenkhachhang = new javax.swing.JTextField();
		lbldiachi = new javax.swing.JLabel();
		txtdiachi = new javax.swing.JTextField();
		lblngay = new javax.swing.JLabel();
		txtngay = new javax.swing.JTextField();
		jScrollPane2 = new javax.swing.JScrollPane();
		tableModelCTHD = new javax.swing.JTable();
		btnthemsanpham = new javax.swing.JButton();
		btnthemhoadon = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		lbltenkhachhang.setText("Tên khách hàng :");

		txtsodienthoai.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtsodienthoaiActionPerformed(evt);
			}
		});

		lblsodienthoai.setText("Số điện thoại :");

		lbldiachi.setText("Địa chỉ :");

		lblngay.setText("Ngày :");
		model = new DefaultTableModel(columnNames, 0);

		tableModelCTHD.setModel(model);
		jScrollPane2.setViewportView(tableModelCTHD);

		btnthemsanpham.setText("Chọn sản phẩm ở đây");
		btnthemsanpham.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnthemSanPhamActionPerformed(evt);
			}
		});

		btnthemhoadon.setText("Thêm hóa đơn");
		btnthemhoadon.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnthemhoadonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(10, 10, 10).addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(btnthemsanpham)
								.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
												jPanel1Layout.createSequentialGroup().addComponent(lbldiachi)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE,
																196, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
												jPanel1Layout.createSequentialGroup().addComponent(lblsodienthoai)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(txtsodienthoai)))
										.addGap(50, 50, 50)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addComponent(lbltenkhachhang)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(txttenkhachhang,
																javax.swing.GroupLayout.PREFERRED_SIZE, 150,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(jPanel1Layout.createSequentialGroup().addComponent(lblngay)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(txtngay)))))
						.addComponent(btnthemhoadon)
						.addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
						.addContainerGap(10, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addGap(7, 7, 7)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txtsodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblsodienthoai)
								.addComponent(txttenkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lbltenkhachhang))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lbldiachi)
								.addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblngay).addComponent(txtngay, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(20, 20, 20).addComponent(btnthemsanpham).addGap(10, 10, 10)
						.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(10, 10, 10).addComponent(btnthemhoadon).addContainerGap(10, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>

	protected void btnthemhoadonActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
		String sodienthoai = txtsodienthoai.getText();
		String tenkhachhang = txttenkhachhang.getText();
		String diachi = txtdiachi.getText();
		String ngay = txtngay.getText();

		KhachHang khachHang = new KhachHang();
		khachHang.setTenkhachhang(tenkhachhang);
		khachHang.setSodienthoai(sodienthoai);
		khachHang.setDiachi(diachi);
		khachHangService.add(khachHang);

		// ngày hiện tại
		Date date = new Date();
		date = new Date(date.getTime());
		SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
		String ngayhientai = sdf.format(date);

		HoaDon hoaDon = new HoaDon();
		hoaDon.setKhachHang(khachHang);
		hoaDon.setNgaylaphoadon(date);
		hoaDon.setTrangthaithanhtoan(true);
		hoaDonService.add(hoaDon);

		List<ChiTietHoaDon> list = new ArrayList<>();
		for (int i = 0; i < tableModelCTHD.getRowCount(); i++) {
			String tensp = tableModelCTHD.getValueAt(i, 1).toString();
			SanPham sp = sanphamservice.findByName(tensp);
			int soluong = Integer.parseInt(tableModelCTHD.getValueAt(i, 3).toString());
			ChiTietHoaDon chiTietHoaDon = new ChiTietHoaDon();
			chiTietHoaDon.setSanPham(sp);
			chiTietHoaDon.setHoaDon(hoaDon);
			chiTietHoaDon.setSoLuong(soluong);
			chiTietHoaDonService.addChiTietHoaDon(chiTietHoaDon);
			list.add(chiTietHoaDon);
		}
		JOptionPane.showMessageDialog(null, "Tạo hóa đơn thành công");
		UIHoadon hoadon2 = new UIHoadon();
		hoadon2.setVisible(true);
		dispose();

	}

	private void txtsodienthoaiActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void btnthemSanPhamActionPerformed(java.awt.event.ActionEvent evt) {
		ModelDanhSachSanPham danhSachSanPham = new ModelDanhSachSanPham(null);
		danhSachSanPham.setVisible(true);
		dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ModelCreateHoaDon.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ModelCreateHoaDon.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ModelCreateHoaDon.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ModelCreateHoaDon.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ModelCreateHoaDon(null).setVisible(true);
			}
		});
	}

	public void addSanPhamVaoHoaDon(SanPham sanPham, int soluong) {
		// ChiTietHoaDon chiTietHoaDon = new ChiTietHoaDon();
		// chiTietHoaDon.setSanPham(sanPham);
		// chiTietHoaDon.setSoLuong(soluong);
		// chiTietHoaDon.setDonGia(sanPham.getGia());
		// chiTietHoaDon.setThanhTien(sanPham.getGia()*soluong);
		// chiTietHoaDon.setHoaDon(hoaDon);
		// hoaDon.getChiTietHoaDons().add(chiTietHoaDon);
		// hoaDon.setTongTien(hoaDon.getTongTien()+chiTietHoaDon.getThanhTien());
		// hoaDon.setTongSoLuong(hoaDon.getTongSoLuong()+chiTietHoaDon.getSoLuong());
		DefaultTableModel model = (DefaultTableModel) tableModelCTHD.getModel();
		Object[] row = new Object[5];
		row[0] = sanPham.getMasanpham();
		row[1] = sanPham.getTensanpham();
		row[2] = soluong;
		row[3] = sanPham.getGia();
		row[4] = sanPham.getGia() * soluong;
		model.addRow(row);
		tableModelCTHD.setModel(model);
		tableModelCTHD.updateUI();
	}

	public JTable getTable() {
		return tableModelCTHD;
	}

	public DefaultTableModel getModelTable() {
		return model;
	}

	// Variables declaration - do not modify
	private javax.swing.JButton btnthemhoadon;
	private javax.swing.JButton btnthemsanpham;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JLabel lbldiachi;
	private javax.swing.JLabel lblngay;
	private javax.swing.JLabel lblsodienthoai;
	private javax.swing.JLabel lbltenkhachhang;
	private javax.swing.JTable tableModelCTHD;
	private javax.swing.JTextField txtdiachi;
	private javax.swing.JTextField txtngay;
	private javax.swing.JTextField txtsodienthoai;
	private javax.swing.JTextField txttenkhachhang;
	// End of variables declaration
}
